<?php

declare(strict_types=1);

namespace Zairakai\LaravelDevTools\Console\Commands\Dev;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Command to clean files generated by Laravel IDE Helper packages.
 *
 * Handles:
 * - _ide_helper.php, _ide_helper_models.php, .phpstorm.meta.php
 * - Compiled Blade views
 * - Bootstrap cache files
 */
final class CleanAfterIdeHelperCommand extends Command
{
    protected $description = 'Clean up files generated by Laravel IDE Helper packages';

    protected $signature = 'dev-tools:clean-ide-helper
                            {--dry-run : Show what would be cleaned without making changes}';

    /**
     * Files generated by IDE Helper packages.
     *
     * @var array<int, string>
     */
    private array $ideHelperFiles = [
        '_ide_helper.php',
        '_ide_helper_models.php',
        '.phpstorm.meta.php',
    ];

    /**
     * Allow command to be invoked as a callable.
     *
     * @codeCoverageIgnore Simple proxy method - tested via handle()
     */
    public function __invoke(): void
    {
        $this->handle();
    }

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $dryRun = (bool) $this->option('dry-run');

        $this->info('Cleaning IDE Helper generated files…');

        if ($dryRun) {
            $this->warn('DRY RUN: No files will be deleted');
        }

        $cleanedCount = 0;
        $cleanedCount += $this->cleanIdeHelperFiles($dryRun);
        $cleanedCount += $this->cleanCompiledViews($dryRun);
        $cleanedCount += $this->cleanBootstrapCache($dryRun);

        $this->displaySummary($cleanedCount, $dryRun);
    }

    /**
     * Clean bootstrap cache files.
     */
    private function cleanBootstrapCache(bool $dryRun): int
    {
        $cachePath = $this->laravel->bootstrapPath('cache');

        if (! File::isDirectory($cachePath)) {
            // @codeCoverageIgnoreStart
            return 0;
            // @codeCoverageIgnoreEnd
        }

        $cacheFiles = collect(File::allFiles($cachePath))
            ->filter(fn ($file): bool => $file->getExtension() === 'php')
            ->filter(fn ($file): bool => $file->getFilename() !== '.gitignore');

        if ($cacheFiles->isEmpty()) {
            return 0;
        }

        $count = $cacheFiles->count();

        if ($dryRun) {
            $this->line(sprintf('Would delete %d bootstrap cache files', $count));
        }
        else {
            foreach ($cacheFiles as $cacheFile) {
                File::delete($cacheFile->getRealPath());
            }

            $this->line(sprintf('Deleted %d bootstrap cache files', $count));
        }

        return $count;
    }

    /**
     * Clean compiled Blade view files.
     */
    private function cleanCompiledViews(bool $dryRun): int
    {
        $viewPath = $this->laravel->storagePath('framework/views');

        if (! File::isDirectory($viewPath)) {
            // @codeCoverageIgnoreStart
            return 0;
            // @codeCoverageIgnoreEnd
        }

        $filesCount = count(File::files($viewPath));

        if (0 === $filesCount) {
            return 0;
        }

        if ($dryRun) {
            $this->line(sprintf('Would delete %d compiled view files', $filesCount));
        }
        else {
            File::cleanDirectory($viewPath);

            $this->line(sprintf('Deleted %d compiled view files', $filesCount));
        }

        return $filesCount;
    }

    /**
     * Clean IDE Helper generated files in the project root.
     */
    private function cleanIdeHelperFiles(bool $dryRun): int
    {
        $basePath     = $this->laravel->basePath();
        $cleanedCount = 0;

        foreach ($this->ideHelperFiles as $ideHelperFile) {
            $filePath = $basePath . DIRECTORY_SEPARATOR . $ideHelperFile;

            if (! File::exists($filePath)) {
                continue;
            }

            $cleanedCount++;

            if ($dryRun) {
                $this->line('Would delete: ' . $ideHelperFile);
            }
            else {
                File::delete($filePath);

                $this->line('Deleted: ' . $ideHelperFile);
            }
        }

        return $cleanedCount;
    }

    /**
     * Display summary and suggestions after cleanup.
     */
    private function displaySummary(int $cleanedCount, bool $dryRun): void
    {
        if (0 === $cleanedCount) {
            $this->info('No IDE Helper files found to clean.');

            return;
        }

        $action = $dryRun
            ? 'Would clean'
            : 'Cleaned';

        $this->info(sprintf('%s %d files.', $action, $cleanedCount));

        if ($dryRun) {
            return;
        }

        $this->newLine();
        $this->comment('Consider running these additional cleanup commands:');
        $this->comment('  php artisan config:clear');
        $this->comment('  php artisan route:clear');
        $this->comment('  php artisan view:clear');
        $this->comment('  composer dump-autoload');
    }
}
