# Variables - Zairakai Tooling
# Shared configuration and styling

# Critical path detection - works from any inclusion depth
LARAVEL_DIRECTORY_TOOLS_MAKE_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
LARAVEL_DIRECTORY_TOOLS_PACKAGE_ROOT := $(abspath $(LARAVEL_DIRECTORY_TOOLS_MAKE_DIR)../../)/
LARAVEL_DIRECTORY_TOOLS_SCRIPTS_DIR := $(LARAVEL_DIRECTORY_TOOLS_PACKAGE_ROOT)scripts/
LARAVEL_DIRECTORY_TOOLS_TOOLS_SCRIPTS_DIR := $(LARAVEL_DIRECTORY_TOOLS_PACKAGE_ROOT)tools/scripts/

# Project root (caller context). Prefer $(shell pwd) over $(CURDIR).
LARAVEL_DIRECTORY_TOOLS_PROJECT_ROOT ?= $(shell pwd)

# Validate paths exist
ifeq ($(wildcard $(LARAVEL_DIRECTORY_TOOLS_SCRIPTS_DIR)),)
$(error Zairakai scripts directory not found: $(LARAVEL_DIRECTORY_TOOLS_SCRIPTS_DIR))
endif

# Project information (can be overridden in project Makefile BEFORE including core.mk)
LARAVEL_DIRECTORY_TOOLS_PROJECT_NAME ?= Zairakai Project
LARAVEL_DIRECTORY_TOOLS_TWITCH_URL ?= https://twitch.tv/zairakai
LARAVEL_DIRECTORY_TOOLS_GITLAB_URL ?= https://gitlab.com/zairakai

# Help styling
LARAVEL_DIRECTORY_TOOLS_HELP_WIDTH := 70

# ANSI Colors (only used in Make, no export)
LARAVEL_DIRECTORY_TOOLS_COLOR_RESET := \033[0m
LARAVEL_DIRECTORY_TOOLS_COLOR_HEADER_BG := \033[46m
LARAVEL_DIRECTORY_TOOLS_COLOR_HEADER_FG := \033[1;37m
LARAVEL_DIRECTORY_TOOLS_COLOR_SECTION := \033[1;33m
LARAVEL_DIRECTORY_TOOLS_COLOR_TARGET := \033[32m
LARAVEL_DIRECTORY_TOOLS_COLOR_FOOTER_BG := \033[44m
LARAVEL_DIRECTORY_TOOLS_COLOR_FOOTER_FG := \033[1;37m

# Export only what shell scripts need
export LARAVEL_DIRECTORY_TOOLS_PROJECT_ROOT
export LARAVEL_DIRECTORY_TOOLS_PACKAGE_ROOT
export LARAVEL_DIRECTORY_TOOLS_SCRIPTS_DIR
export LARAVEL_DIRECTORY_TOOLS_TOOLS_SCRIPTS_DIR
export LARAVEL_DIRECTORY_TOOLS_PROJECT_NAME
export LARAVEL_DIRECTORY_TOOLS_TWITCH_URL
export LARAVEL_DIRECTORY_TOOLS_GITLAB_URL
