#!/usr/bin/env bash
#
# Zairakai Laravel Dev Tools - Package Uninstall Script
# Removes files installed by setup-package.sh
#
# Usage:
#   bash uninstall-package.sh           # Interactive mode (ask before removing)
#   bash uninstall-package.sh --force   # Force mode (remove without asking)
#

set -euo pipefail

# ============================================================================
# Bootstrap
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "${SCRIPT_DIR}/config.sh"

# ============================================================================
# Arguments Parsing
# ============================================================================

FORCE_MODE=false

for arg in "$@"; do
    case "$arg" in
        --force|-f)
            FORCE_MODE=true
            ;;
        --help|-h)
            echo "Usage: $0 [--force]"
            echo ""
            echo "Removes files installed by setup-package.sh:"
            echo "  - Makefile (only if not manually customized)"
            echo "  - .editorconfig"
            echo "  - phpstan.neon (only if not manually customized)"
            echo "  - config/dev-tools/ directory (published configs)"
            echo "  - .githooks/ directory (if installed)"
            echo ""
            echo "The following are NOT removed:"
            echo "  - composer.json (scripts added by the plugin)"
            echo ""
            echo "Options:"
            echo "  --force, -f    Remove without confirmation"
            echo "  --help, -h     Show this help message"
            exit 0
            ;;
        *)
            log_error "Unknown option: $arg"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# ============================================================================
# Main
# ============================================================================

uninstall_package() {
    log_header "🗑️  Package Development Uninstall"

    if [[ "$FORCE_MODE" != "true" ]]; then
        log_warning "This will remove files installed by setup-package.sh"
        echo ""
        read -r -p "Are you sure? [y/N] " response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            log_info "Uninstall cancelled"
            exit 0
        fi
        echo ""
    fi

    local removed=0
    local skipped=0

    log_step "Removing development files..."
    echo ""

    # ============================================================================
    # Makefile — remove only if it still matches the stub (not customized)
    # ============================================================================

    local makefile="${PROJECT_ROOT}/Makefile"
    local makefile_stub="${PROJECT_ROOT}/vendor/zairakai/laravel-dev-tools/stubs/Makefile.stub"

    if [[ -f "$makefile" ]]; then
        if [[ -f "$makefile_stub" ]] && diff -q "$makefile" "$makefile_stub" > /dev/null 2>&1; then
            rm -f "$makefile"
            log_success "  Removed Makefile"
            removed=$((removed + 1))
        else
            log_info "  Makefile was customized — skipping (remove manually if needed)"
            skipped=$((skipped + 1))
        fi
    fi

    # ============================================================================
    # .editorconfig — always safe to remove (it's a copy, not user-customized)
    # ============================================================================

    local editorconfig="${PROJECT_ROOT}/.editorconfig"

    if [[ -f "$editorconfig" ]]; then
        rm -f "$editorconfig"
        log_success "  Removed .editorconfig"
        removed=$((removed + 1))
    fi

    # ============================================================================
    # phpstan.neon — remove only if it was auto-generated (contains our marker)
    # ============================================================================

    local phpstan_neon="${PROJECT_ROOT}/phpstan.neon"

    if [[ -f "$phpstan_neon" ]]; then
        if grep -q "Generated by laravel-dev-tools setup" "$phpstan_neon" 2>/dev/null; then
            rm -f "$phpstan_neon"
            log_success "  Removed phpstan.neon (auto-generated)"
            removed=$((removed + 1))
        else
            log_info "  phpstan.neon was customized — skipping (remove manually if needed)"
            skipped=$((skipped + 1))
        fi
    fi

    # ============================================================================
    # config/dev-tools/ — published configs directory
    # ============================================================================

    local dev_tools_dir="${PROJECT_ROOT}/config/dev-tools"

    if [[ -d "$dev_tools_dir" ]]; then
        local file_count
        file_count=$(find "$dev_tools_dir" -type f | wc -l | tr -d ' ')

        if [[ "$FORCE_MODE" == "true" ]]; then
            rm -rf "$dev_tools_dir"
            log_success "  Removed config/dev-tools/ (${file_count} files)"
            removed=$((removed + 1))
        else
            log_warning "  config/dev-tools/ contains ${file_count} published config(s)"
            echo ""
            read -r -p "  Remove config/dev-tools/ and all its contents? [y/N] " response
            if [[ "$response" =~ ^[Yy]$ ]]; then
                rm -rf "$dev_tools_dir"
                log_success "  Removed config/dev-tools/"
                removed=$((removed + 1))
            else
                log_info "  Kept config/dev-tools/"
                skipped=$((skipped + 1))
            fi
        fi
    fi

    # ============================================================================
    # .githooks/ — versioned git hooks directory
    # ============================================================================

    local hooks_dir="${PROJECT_ROOT}/.githooks"

    if [[ -d "$hooks_dir" ]]; then
        rm -rf "$hooks_dir"
        log_success "  Removed .githooks/"
        removed=$((removed + 1))

        # Reset git hooks path to default if it was set to .githooks
        if [[ -d "${PROJECT_ROOT}/.git" ]]; then
            local current_hooks_path
            current_hooks_path="$(cd "${PROJECT_ROOT}" && git config core.hooksPath 2>/dev/null || echo "")"

            if [[ "$current_hooks_path" == ".githooks" ]]; then
                (cd "${PROJECT_ROOT}" && git config --unset core.hooksPath)
                log_success "  Reset git config core.hooksPath to default"
            fi
        fi
    fi

    # ============================================================================
    # Summary
    # ============================================================================

    echo ""
    log_header "✅ Uninstall completed"
    echo ""
    log_info "Removed: ${removed} item(s), skipped: ${skipped} item(s)"
    echo ""
    log_info "Note: composer.json scripts were not modified"
    echo ""
}

# ============================================================================
# Execute
# ============================================================================

uninstall_package
